### ISSUE TITLE
关于记忆语法的问题

### ISSUE THREAD

**Issue by htmlcssscript** [byoungd/english-level-up-tips-for-Chinese#1]
背完单词 **多久** 背语法？
还有那些链接打不开 不知道是我宽带的问题还是别的问题。

**Comment by mazhaoyu** [comment]
1.语法方面 我会单独写一些经验，至于是 *多久* 不是很容易回答
2.链接大部分被墙了 我有时间的话可以转载一部分到国内的视频网站网站上

**Comment by byoungd** [comment]
视频大部分为YouTube链接（被国内墙了），所以你需要用梯子来访问
