### ISSUE TITLE
hello i speak chinese and english, let me know how i can help

### ISSUE THREAD

**Issue by sw-yx** [byoungd/english-level-up-tips-for-Chinese#12]
if you are looking to go from level B2 to C1 and above I would be happy to help with any questions.

**Comment by coldnight** [comment]
First, my English is very bad, but I feel bad when I see the incorrect uppercase usage. Is that not important?

**Comment by sw-yx** [comment]
it depends on the context. if it is informal, then case is not important. if it is formal, then yes it is. make sense?
