### ISSUE TITLE
微信公众号大数据文摘（微信ID:bigdatadigest）申请转载

### ISSUE THREAD

**Issue by huiyiguniang** [byoungd/english-level-up-tips-for-Chinese#13]
您好，我是微信公众号大数据文摘（微信ID:bigdatadigest）的编辑，看到了您的这篇文章，觉得非常有趣并且实用，想要在微信公众号上转载发布，我们会在文章中注明来源和作者，还烦请您允许。当然，如果您有其他转载需求，也可以告诉我，谢谢。

PS大数据文摘是大数据行业排名第一的微信公众号，目前有四十三万粉丝，非盈利公益媒体，致力于传播数据文化。

万分感谢

**Comment by byoungd** [comment]
仅需注明来源与作者即可，没有其他要求。
转载吧。

**Comment by huiyiguniang** [comment]
好的，非常感谢。
转载后我会将链接发送到这里，同时也欢迎您关注大数据文摘
谢谢啦！

**Comment by huiyiguniang** [comment]
您好，非常感谢您的文章，这是我们的转载链接：http://mp.weixin.qq.com/s/pT67T0fAwJNJtKFoxnc3XQ
目前发布8小时已经有一万多阅读量，38条点赞和24条精选留言。有眼光的读者说，作者整理了这么多这么长的文章，一定花费了不少时间。好文建议收藏。谢谢。

**Comment by RayJune** [comment]
良心作者 点赞 👍

**Comment by byoungd** [comment]
我看到啦，图片因为没有针对移动版进行优化，阴影效果没去（章节导航的图），或许以后这份指南完结后，我可以帮忙针对移动版重新优化一下

**Comment by huiyiguniang** [comment]
对对对，后台也有粉丝提出这个问题了，我在编辑的时候没有发现呢，推送以后才有的黑框框。不过文章非常好，一点点小问题真是一点也不影响呢。非常感谢作者的良心分享。

**Comment by xiaoaojianghu** [comment]
这转载是不是有点无耻, 只有很小的灰色文字提示"经作者授权转载"和原文链接, 普通读者根本注意不到, 文中广告却是一个大图片. 最重要的是"阅读原文"跳到你们的课程购买页面, wtf
