### ISSUE TITLE
请问初学者单词表在哪

### ISSUE THREAD

**Issue by nothingp** [byoungd/English-level-up-tips-for-Chinese#18]
请问初学者单词表在哪

**Comment by byoungd** [comment]
1.还未完成

2.由于列出的这部分语言的官方文档我大部分都已经看过了，不少生词会漏掉，所以在筛选生词方面希望能有刚接触这门语言文档的人来提供

**Comment by mikumikulch** [comment]
十分期待这份单词表。博主加油。

**Comment by sorz** [comment]
不知道单词入选标准是什么。可能适合用程序生成？
