### ISSUE TITLE
一周2000+star怎么做到的

### ISSUE THREAD

**Issue by zhangxiaoshang** [byoungd/English-level-up-tips-for-Chinese#20]
这个repo建了才一周就有2000+star，怎么做到的？还是说我看错了？github的star不是挺稀少的吗？

**Comment by byoungd** [comment]
1.感谢来自v2ex社区程序员的第一波收藏
2.感谢开发者头条的推荐
3.感谢为此指南做出贡献的朋友
3.我的确很用心的在完善这份文档

**Comment by RayJune** [comment]
个人觉得这是一份有灵魂的repo（已star）

**Comment by jiafuweiJava** [comment]
可以看得出作者在很用心的整理

**Comment by bailicangdu** [comment]
这是一个非常不错的教程，10k都值

**Comment by hackjutsu** [comment]
果断帮顶！

**Comment by trexguo** [comment]
内容还需要进一步充实

**Comment by wangmeijian** [comment]
看得出很用心，star

**Comment by AAChartModel** [comment]
良心 repo,10000+的 star 也不嫌多啊
