### ISSUE TITLE
其实国内英语甚至是外语教学的最大问题是

### ISSUE THREAD

**Issue by iVanilla** [byoungd/english-level-up-tips-for-Chinese#21]
国内使用的英语/外语教学方法还是古老的硬背单词表和死记语法。

这是多个世纪之前英国士兵学习西班牙语的方法。

它的特点是十分低效，很难培养语感。所以当我们听外语或者跟老外交流时，会本能地把外语先翻译成母语，用母语思维理解之后，如果是交流，再翻译成外语说出来。

这样的最大弊端就是很耗时间，导致即使对方是正常语速，你也很难听清楚和理解后面部分的内容。

现在有些老师开始提倡英语/外语思维，这是个很大的进步，所以除非有必要，尽量不要通过翻译来理解意思。

现在有些老师走进了一个误区，强调听说读写译应该同时学习，其实这是不对的，应该循序渐进，先听说后读写，最后才是翻译，而且这些都要建立在语感上面。

最后推荐一个强大牛逼的软件，相信不少人已经听说过甚至使用过，它就是大名鼎鼎的**Rosetta Stone**。 它使用“沉浸式教学”设计，利用带有图像的卡片和做选择题的形式进行单词和语法教学，可以纠正你的不准确的读音，甚至可以练习写作。只要你掌握了一门语言最基础的单词表(汉语是汉语拼音表)就可以使用Rosetta Stone入门上路开始学习这门外语了。

**Comment by byoungd** [comment]
可悲的情况主要是，老师知道英语思维好啊，但是并不会去实践，因为他们相信他们老一套的方法能让学生考高分。

提倡英语思维，更多的只是嘴上说说而已，任重道远。

**Comment by iVanilla** [comment]
@byoungd 归根结底还是应试教育啊

**Comment by nshen** [comment]
按照正文单词篇说的

>背单词的回报率是递减的

`7000词汇量` 可以理解  `90%`  英语内容，而到 `50000 词汇量` 才能理解 `95%` 

所以前7000还是要背，后边就不推荐背了吧

**Comment by byoungd** [comment]
@nshen 7千词汇量在面对英美剧还是有些捉襟见肘 条件允许 依然推荐继续扩充词汇量

**Comment by lejourbonne** [comment]
说句不pc的话，大部分人应该感谢应试教育，背单词和背语法绝对是性价比最高，起效最快的方法，只是有些人坚持下来了，有些人中途因为枯燥就放弃了。

**Comment by hackjutsu** [comment]
在美国呆了四年多了，不知道什么是“英语思维”……

要真说有区别的话，就是老美讨论问题一般就事论事，关于问题细节讨论地很深入；而我们讨论问题时，前半段还能就事论事，后半段就开始讨论对方是否有足够资历和自己讨论问题……

参考issue：https://github.com/byoungd/english-level-up-tips-for-Chinese/issues/24

**Comment by iVanilla** [comment]
@nshen 背单词是不可避免的，我反对的死记硬背，太没效率了，应该结合相关事物来记忆再背下来，这样更容易记住而且不易忘记。

至于词汇量，一般来说，其实每种语言有大约10%的不太常用的词汇是专有名词和专业术语，如果用不到的话，能不记还是不要刻意去记了，现在有些人批评四六级考试，因为里面很多单词可能一辈子也用不到，但是不背就无法考过。

**Comment by iVanilla** [comment]
@hackjutsu 我说那个楼主图样，只是因为想膜一下，而且那位楼主确实思想死板，墨守成规。

英语(外语)思维指的是，在平时(不一定是跟老外交流)都使用英语来思考问题，而不是都用汉语(母语)思维。

**Comment by byoungd** [comment]
关于这个话题 大家就仁者见仁智者见智吧 如果想要深入讨论 烦请私下沟通

深表感谢

**Comment by lejourbonne** [comment]
四六级单词一辈子用不到？真的喷了。

**Comment by iVanilla** [comment]
@lejourbonne 请问您有认真看过我的原文吗？

> 现在**有些人**批评四六级考试，因为里面**很多**单词**可能**一辈子也用不到

我用粗体字标出重点了，自己好好理解吧，而且我说的前提条件是是**在日常生活中**，如果您主要是跟教授等专业人士打交道，经常要写使用大量专业术语的论文，那当我没说。
