### ISSUE TITLE
死记硬背单词和语法是无法避免的

### ISSUE THREAD

**Issue by lejourbonne** [byoungd/english-level-up-tips-for-Chinese#24]
得，帮顶了。

**Comment by iVanilla** [comment]
我就是那个提出不要死记硬背单词表和语法的人。

首先这是一种低效落后的学习方法。

其次，通过这种机械的方式记下来的单词和语法，由于方法不得当，很容易遗忘，不利于培养形成语感。

然后，因为你习惯看单词表和语法，在你用英语或者其他外语听说读写时，**由于大脑使用你的母语作为单词和它表达的事物作为彼此联系的桥梁，会导致你自然而然地先把外语翻译成母语，用母语思维去理解，然后再翻译成外语表达出来**。

这个过程中，首先是把外语翻译过来，因为有母语的语感，你不需要重新组织单词，就能理解句子的大致意思，这个过程不会花多少时间。

**在回翻译的过程中，你“熟背”的单词表和语法知识会起主导作用**，你会先用母语组织好句子，然后用外语的语法拼装一遍，这个过程很花时间，比你从外语翻译成母语要长不少。这是因为**你死记硬背不能帮助你形成语感**，如果你有语感需要仔细挑选单词和组织语法吗？这是水到渠成的事情。

最后说一句，楼主毕竟还是Too young，墨守成规没有任何好处。

**Comment by hackjutsu** [comment]
个人经验最有效的学习方法是幻想自己和外国人辩论，然后准备辩词。

**Comment by lejourbonne** [comment]
2楼所说的只是理想化的场景吧，没有完全沉浸在母语环境下（比如出国留学工作），或者在各大外国语学校读书，根本无法顺利的进行。就连你想用英英词典去进一步查看进阶单词的解释，你也需要至少3000词汇量，而且这些单词基本和词根词缀无关，不“死记硬背”，如何进阶？就算你去用构词法（词根词缀）背诵单词，也需要死记硬背大量的词根词缀，毕竟它们和生活没有任何的联系，而各种xx单词书里的“牵强附会”的记忆法只会增加混乱程度，还不如大量反复重复有用。死记硬背和灵活运用是不矛盾的。
英语语法相对简单，口语中涉及到的时态也不多，你可以去了解下法语的语法，不背好变位各种虚拟式能开口算我输。
我不知道我雅思7.5，GRE 330/340，法语TEF B2的成绩算不算是”Too Young“，但我知道如果不死记硬背单词（说是死记硬背，实际上是反复利用艾宾浩斯遗忘曲线和闭着眼睛过单词反复刺激视觉和听觉，现在更有百词斩或者手动搜索单词图片这类图像上的刺激），考试的时候就会是“dkkdkd kakaka，烫烫烫”各种乱码。
当然，词表我会选择英-英解释的或者英-法解释的，并用其造句，使得词语直接和生活联系起来。
语感也可以通过大量反复背诵和听写优秀材料（如新概念3，4 120篇，简明法语42篇，走遍美国，走遍法国，老友记，Une fille et un garcon的音频，各种生活类podcast）来获得。
还是那句老话，Easier said than done。

**Comment by iVanilla** [comment]
虽然楼主删掉了之前那段强调背单词和语法的重要性的论述，但我还是要说一下，楼主走进的误区是什么。

**我没有说不要背单词，而是死记硬背单词是非常低效的**，因为我在issues #21 中也提到了，熟背单词表之后，你很容易在实际运用外语时，下意识地在大脑中把外语和母语相互翻译，拖延时间，影响交流效率。

**单词当然是要背的，但不应该死记硬背，而是应该通过单词有关的事物来加强记忆和理解。**我们每个人都是从小开始学习母语的，那时你会去看单词表吗？是死记硬背单词吗？最后还不是把母语学会了？看懂字典词典不是问题吧？

至于语法，**只要你多看老外之间交流，多创造外语环境，语感迟早会积累形成的。**我从来就没有学习过什么汉语语法，更没有刻意去记忆甚至背诵什么主谓宾语什么乱七八糟的概念这些语法知识，但这丝毫没有影响妨碍我和别人交流和阅读写作。

**语感的形成是水到渠成的过程，不能急功近利，更不是靠死记硬背单词语法培养出来的。**

**Comment by fffx** [comment]
看看这个网站是如何解释一个单词的 https://www.vocabulary.com

**Comment by lejourbonne** [comment]
冒昧的问下iVanilla 的标准化成绩（比如四六级，公共英语，雅思托福，托业，PTE等等）或者生活经历，因为无法面对面交流，除了标准化考试分数之外无法评判对方的语言水平。如果我四级刚过，您雅思8分，您说谁的经历会更有参考价值？语言环境不是谁都有的，有人能留学美加，可对多少人来说，是多遥不可及啊。

我自己亮出自己的成绩是为了说明我阐述的方法可行，当初为了学习语言，我还专门找了在英读TESOL的朋友请教，也自己学习了解了二语习得理论，并多次试错，才保证了效果。

我并无“下半场就开始降维讨论双方是否有足够资历来讨论问题……”的意思，既然一个层主扣帽子“too young”（这不是下半场就开始降维讨论双方是否有足够资历来讨论问题……”的这种攻击情况吗？），另外一个层主扣帽子“下半场就开始降维讨论双方是否有足够资历来讨论问题……”，这样我自然没有讨论和分享的必要了，呵呵，大家各自有各自的学习方法，开心就好。

**Comment by iVanilla** [comment]
@lejourbonne 那么请问您在复习应考这些“标准化”考试的时候，是怎样背单词呢？现在能记住掌握的又有多少？

很抱歉，我觉得文科太枯燥，我可没有您那种耐心去死记硬背单词语法，所以我就学习理科去了，我连英语课都在做理科题。

死记硬背单词是形如“Apple：A-P-P-L-E Apple，苹果”这样的机械记忆方式，通过这种方式背下来的单词，很容易在考试之后忘记，因为一是以后基本用不到，二是这种记忆方式违背大脑的记忆规律。

讨论这些所谓标准化成绩没有什么意义，过了四六级甚至雅思托福结果在国外什么都不会说的人大有人在，因为他们顶多只是掌握了阅读写作，把最基本的听和说忽视了，后果不堪设想。

不会学以致用的人，即使外语考试成绩再高又怎么样？也就拿出去装一下逼而已，遇到真的外语环境一样歇菜。

**Comment by byoungd** [comment]
两位保留意见吧

这个issue先关闭了，因为已经打扰到了watch用户。

希望能予以理解，谢谢！

**Comment by lejourbonne** [comment]
@iVanilla 一看您就没接触过雅思托福PTE这类标准化考试，托福雅思都有口语听力部分，这些不是考出来装逼用的，确实非常有作用，比如托福中的高频词可以解决您看日常新闻，经济学人，科学杂志论文的大部分动词和术语，托福雅思听力场景包含了日常生活学习的高频场景（看病，听课，和教授讨论论文，和同学groupwork，旅游，点菜，报名等等）， 托福的作文和雅思作文的part2以及gre的issue，讲述了怎样论述一个观点，雅思作文的part1 就是描述数据表格或者日常应用文（各种信件），托福口语的结构和逻辑性，雅思口语的广度（生活中各方面）都可以作为建立您自己”语料库“的过程，都是生活学习中100%可以用到的，而且这些材料的获取绝对比花时间精力金钱去创造”英语环境“要容易的多，另外gre分析写作的argument部分，就是帮助了解英文（其实中文也适用）中常见的逻辑错误和逻辑讨论的，学习一下大有裨益。

**Comment by iVanilla** [comment]
@lejourbonne 我说的是“不会**学以致用**的人，考得再好也只能出去装逼”，我完全没有否认考试所背的单词没有用，只是**在日常生活中**大多数词汇是用不到的，但如果您主要跟教授之类的专业人士交流，经常要写论文，用到很多专业术语，那掌握这些单词当然是很重要的。

说来说去，我们讨论的都不在一个点上，**背单词没有错，但死记硬背却是吃力不讨好的事情**。

**Comment by lejourbonne** [comment]
@iVanilla 既然您都说“四六级”词汇日常都用不到了，我就没和您讨论下去的必要了。

**Comment by leedstyh** [comment]
@byoungd lock吧

**Comment by lejourbonne** [comment]
得，不在这里讨论，祝大家学习顺利。
