### ISSUE TITLE
建议本repo的图片放到CDN上

### ISSUE THREAD

**Issue by Jacob201311** [byoungd/English-level-up-tips-for-Chinese#25]
如题，要不然有时候真的很卡

**Comment by lejourbonne** [comment]
+1

**Comment by zce** [comment]
在 GitHub 上展示的 Markdown 文件是不可以使用 CDN 链接（外链）的，就算在 Markdown 中使用外链的方式引入图片，最终工作时也会被替换为 GitHub 自己的 CDN 链接

例如，以下为 CDN 链入的图片：

![](https://ws1.sinaimg.cn/large/c294db74ly1ffpnk0pkhvj20go0im74y.jpg)

**Comment by Jacob201311** [comment]
试一下http://ooc7v5b7u.bkt.clouddn.com/1497520462.png?imageMogr2/thumbnail/!100p

![](http://ooc7v5b7u.bkt.clouddn.com/1497520462.png?imageMogr2/thumbnail/!100p)

**Comment by byoungd** [comment]
采用github项目内的文件方便更新图片资源文件，稍后会发布一个适合国内用户访问的站点。
