### ISSUE TITLE
能否把youtube上的视频搬到国内？

### ISSUE THREAD

**Issue by zhoukekestar** [byoungd/english-level-up-tips-for-Chinese#27]
访问youtube还是有诸多不便。

**Comment by lejourbonne** [comment]
有版权方面的考虑吧

**Comment by iVanilla** [comment]
有什么不方便的？网上有很多SS/SSR账号，有免费有付费，现在找个梯子不难。

另外想下载YouTube也很简单，用you-get就行，挺方便的。

**Comment by NameYoung** [comment]
自己动手丰衣足食，多多动手挺好的。
做个动手党，少做“伸手党”

**Comment by zhoukekestar** [comment]
有空我自己搬吧，搬完后在提`PR`。只是为了`更`方便地看视频。

**Comment by AAChartModel** [comment]
想法很好,毕竟其实还是有很多人可能会因此错过这么好的分享,能搬运过来,也是一件功德
