### ISSUE TITLE
What kind of training course to spend 20,000 yuan

### ISSUE THREAD

**Issue by FourEyebrowXiake** [byoungd/english-level-up-tips-for-Chinese#29]
有在coursera和Udacity上过课。虽然，这些课都有论坛，有些还有微信群。但是，感觉还是一个人在学。学习效率也不高，碰到问题，缺少解决它的毅力和方法。本身是很像当程序员的。可是都到大三了，水平一直提不上去，很焦虑。

**Comment by atom2ueki** [comment]
first step, communicate with english in github, just kidding but it's true

**Comment by FourEyebrowXiake** [comment]
I went to class at coursera and Udacity. Although these classes have forums, and weixin groups. But the feeling is still a person is study. Learning efficiency is not high. encounter problems, the lack of perseverance and methods to solve it. I want to be a excellent programmer. But I studied in the University for three years ,programming  level has been unable to enhance, very anxious.

**Comment by zhe-he** [comment]
1. 一般讨论要学英语的都是中国人，而且英语还不太好，我觉得这面墙没必要像其他github一样被英文屠版 😂
1. 现在差不多哪个培训班都是2W左右，出来如果能找到工作的话半年就可以还上。 问题是： 越来越多的人加入到这一行业，导致水平参差不齐，大多数都是抱着这行不错的待遇而来，没有考虑自己适不适合这行，很多用人单位一听是培训机构出来的-不要。
1. 如果对这行没有必要的兴趣，不建议入坑。
## 培训过程类似如下： 
> 上午、下午听老师讲课
> 晚上回去重顾老师的内容，完成作业
> 一个月测试总结
> 毕业前完成自己的作品
* 每天可能就是起的比鸡早，睡的比...... *

**Comment by lijunjieone** [comment]
想变好的程序员就去刷题啊.不用焦虑,时间到了.水平也就到了.
