### ISSUE TITLE
星星是不是全来自扯淡篇？

### ISSUE THREAD

**Issue by Bjoux2** [byoungd/english-level-up-tips-for-Chinese#34]
如题

**Comment by AAChartModel** [comment]
您从来不惮以最坏的恶意来揣测别人?

**Comment by tudouloveloli** [comment]
这里不是扯淡区，在这扯啥淡呢

Sent from my iPhone

On Aug 20, 2018, at 18:53, An An <notifications@github.com<mailto:notifications@github.com>> wrote:


您从来不惮以最坏的恶意来揣测别人?
