### ISSUE TITLE
word-list 单词类目疑问

### ISSUE THREAD

**Issue by nanck** [byoungd/english-level-up-tips-for-Chinese#43]
请问 word-list 暂时只收集编程语言类的单词么？是否考虑增加一个“软件工程”的 page 呢，用于收集跟软件开发流程有关的一些单词：团队、需求、测试、版本、编译……。大家来补充哈~。因为这类单词在一些技术文章中出现的频率比较高，尤其是官方的开发者站上。

**Comment by byoungd** [comment]
主要是想要大家来贡献生词表的难度很大
