### ISSUE TITLE
话说...感觉某些内容感觉有歧义啊...

### ISSUE THREAD

**Issue by wfly1998** [byoungd/English-level-up-tips-for-Chinese#56]
不知道是不是我的问题（

认知篇 -> 认识自己的情绪

> 我看到很多人在学习一项技能的时候，有时效率奇高，有如神助，有时却"今天不想学"、"先撸几把"，后者往往占大多数，最终导致放弃。 所以，当我们觉得自己没心思做一件事情的时候，到底是什么在支配我们的意识？

话说这里的`先撸几把`，我们都知道这是去打联盟，但是这里用词感觉有点怪怪的...

（我先去笑一会儿

**Comment by zongxiaomi** [comment]
我擦 一年前关注的这个hub 要不是推送都快忘了，你才98年 思考这么多 惭愧惭愧

**Comment by byoungd** [comment]
@wfly1998 这里的用词的确有不妥之处 我稍后进行修改 感谢提出这个问题

**Comment by wfly1998** [comment]
@zongxiaomi 可能是读得比较认真而且思考得比较多吧（捂脸
