### ISSUE TITLE
没啥用

### ISSUE THREAD

**Issue by xiaowan1993** [byoungd/English-level-up-tips-for-Chinese#60]
我以为是一门英语学习教材，没想到.....没啥用啊

**Comment by Jacob201311** [comment]
是的

**Comment by LovelyBuggies** [comment]
借鉴了很多知乎和贴吧上的思想比如**单词篇**。
笔者还是挺用心的，但是此repo更像是几篇心得，适合发博客，不建议建库。
但是更希望能够整理成英语学习教材，以供参考。

**Comment by byoungd** [comment]
@xiaowan1993 请补充详细说明以证明 **没啥用**

**Comment by ParadiseHell** [comment]
@byoungd 我觉得仁者见仁,智者见智吧,何必解释那么多.
