### ISSUE TITLE
这是我订阅的最失败的项目

### ISSUE THREAD

**Issue by tudouloveloli** [byoungd/English-level-up-tips-for-Chinese#62]
这是我订阅的最失败的项目，项目本身很喜欢，但是issues实在是不忍直视，邮箱频繁被垃圾的聊天内容充满。
issues 不是用来聊天的。
都是些什么人啊。

**Comment by Beeta** [comment]
同感… 已经stop ignoring了…

**Comment by zhe-he** [comment]
有同感的，你是怎么能在半小时的迅速回复的(￣∇￣)
