### ISSUE TITLE
pc版导入「麦克米伦7000词汇」Anki卡后，不显示图片

### ISSUE THREAD

**Issue by Liudon** [byoungd/English-level-up-tips-for-Chinese#76]
![image](https://user-images.githubusercontent.com/5969707/65026056-5b1e8b80-d96a-11e9-84e1-6fa9b2157aad.png)

**Comment by Liudon** [comment]
![image](https://user-images.githubusercontent.com/5969707/65026118-7b4e4a80-d96a-11e9-81db-8d12abd22ef0.png)

**Comment by ShawnYou1** [comment]
看到笔者发的这个工具，我也推荐一个工具，叫Burning Vocabulary，大家自己Google，很好用的一个工具。

**Comment by austin-fan** [comment]
手机端也不展示

**Comment by ethan-YY** [comment]
我这里提示是新版不支持http的图片。。
