### ISSUE TITLE
大佬的求学经历有点牛逼

### ISSUE THREAD

**Issue by c7haoyu** [byoungd/English-level-up-tips-for-Chinese#77]
我不问技术问题，单纯就是过来吹牛逼的 。哈哈哈哈，大佬的学生时代有点东西，干了我一直想干但是不敢的事情！！！

**Comment by zongxiaomi** [comment]
那就继续吹啊

**Comment by byoungd** [comment]
> 我不问技术问题，单纯就是过来吹牛逼的 。哈哈哈哈，大佬的学生时代有点东西，干了我一直想干但是不敢的事情！！！

人生仅仅是一场旅行，我的信条是**敢想敢做**。
