### ISSUE TITLE
重修19门

### ISSUE THREAD

**Issue by wardseptember** [byoungd/English-level-up-tips-for-Chinese#84]
“在我思考如何回答这个问题时，想到了在大四上一学期我考过 26 门课的经验（其中重修 19 门，当前学期 7 门），觉得我应该能勉强提供一些高效学习的小技巧。 在和她交流了一番学习心得后，我惊讶于她在学习方面的热情竟是如此之高，同时也发现她的学习方法有些不可取之处。 ”段子吗大兄弟，不然你是真自信，大学考试不是闭着眼睛就能考过。

**Comment by byoungd** [comment]
> “在我思考如何回答这个问题时，想到了在大四上一学期我考过 26 门课的经验（其中重修 19 门，当前学期 7 门），觉得我应该能勉强提供一些高效学习的小技巧。 在和她交流了一番学习心得后，我惊讶于她在学习方面的热情竟是如此之高，同时也发现她的学习方法有些不可取之处。 ”段子吗大兄弟，不然你是真自信，大学考试不是闭着眼睛就能考过。

真人真事

**Comment by oushu1tanqiang1** [comment]
只能说艺术来源于生活

**Comment by byoungd** [comment]
> “在我思考如何回答这个问题时，想到了在大四上一学期我考过 26 门课的经验（其中重修 19 门，当前学期 7 门），觉得我应该能勉强提供一些高效学习的小技巧。 在和她交流了一番学习心得后，我惊讶于她在学习方面的热情竟是如此之高，同时也发现她的学习方法有些不可取之处。 ”段子吗大兄弟，不然你是真自信，大学考试不是闭着眼睛就能考过。

重修19门并不是多么难的事，只要你掌握了方法和真的利用了时间去执行。

**Comment by wardseptember** [comment]
有手就能过，你是咋重修19门的，可怕，

**Comment by byoungd** [comment]
> 有手就能过，你是咋重修19门的，可怕，

当时创业想做一款互联网产品，没时间上课，当然主要的原因是我们的专业课也不是很难。

**Comment by wardseptember** [comment]
> > 有手就能过，你是咋重修19门的，可怕，
> 
> 当时创业想做一款互联网产品，没时间上课，当然主要的原因是我们的专业课也不是很难。

佩服，还是挺牛逼的

**Comment by byoungd** [comment]
> > > 有手就能过，你是咋重修19门的，可怕，
> > 
> > 
> > 当时创业想做一款互联网产品，没时间上课，当然主要的原因是我们的专业课也不是很难。
> 
> 佩服，还是挺牛逼的

有空看看本repo的番外篇 让你从另一个侧面了解我
