### ISSUE TITLE
请停止你的作恶行为

### ISSUE THREAD

**Issue by NE-SmallTown** [byoungd/English-level-up-tips-for-Chinese#85]
你要怎么装逼，吹嘘和膨胀是你自己的事。但在公开场合，请删除所有已发布的女生的隐私信息（包括其它平台），还 TM 照片到处发，发漏了[还特地补一张](https://github.com/byoungd/English-level-up-tips-for-Chinese/commit/340dab90196ea857c18deae96c677a30e7119c0d)，还[专门开专栏同步推送到知乎](https://www.zhihu.com/column/c_1447635258011660288)，你什么目的？

![image](https://user-images.githubusercontent.com/18418010/143673419-abe02d15-1021-4327-98ac-8067c1cf7c00.png)

这么怕没人看？有本事开你的法拉利出来炫耀啊，哦，对不起，忘了你是创业老总 CEO，不稀罕这些，还是抠着脚感叹该死的爱情在网络上装逼比较符合你的气质。

**Comment by byoungd** [comment]
戾气太重。
稍安勿躁。

**Comment by NE-SmallTown** [comment]
读过书没，上过学没，你爹妈是不是没教过你怎么做人，你的 CEO 是躲在裤裆里当的吗？你怎么还一副自我感觉良好的样子啊？你是很享受这种严重地侵害她人权益后还有逼脸轻飘飘的一句「戾气太重」的快感，还是把这当做一种更加热血沸腾的炫耀？

你是有病，还是变态？

这里你最后改过自新的机会，望珍重。

**Comment by byoungd** [comment]
> 读过书没，上过学没，你爹妈是不是没教过你怎么做人，你的 CEO 是躲在裤裆里当的吗？你怎么还一副自我感觉良好的样子啊？你是很享受这种严重地侵害她人权益违法犯罪后还有逼脸轻飘飘的一句「戾气太重」的快感，还是把这当做一种更加热血沸腾的炫耀？
> 
> 你是有病，还是变态？
> 
> 这里你最后改过自新的机会，望珍重。

我郑重声明一下 本文出现的图片都是经过授权的！

**Comment by byoungd** [comment]
> 你要怎么装逼，吹嘘和膨胀是你自己的事。但在公开场合，请删除所有已发布的女生的隐私信息（包括其它平台），还 TM 照片到处发，发漏了[还特地补一张](https://github.com/byoungd/English-level-up-tips-for-Chinese/commit/340dab90196ea857c18deae96c677a30e7119c0d)，还[专门开专栏同步推送到知乎](https://www.zhihu.com/column/c_1447635258011660288)，你什么目的？
> 
> ![image](https://user-images.githubusercontent.com/18418010/143673419-abe02d15-1021-4327-98ac-8067c1cf7c00.png)
> 
> 这么怕没人看？有本事开你的法拉利出来炫耀啊，哦，对不起，忘了你是创业老总 CEO，不稀罕这些，还是抠着脚感叹该死的爱情在网络上装逼比较符合你的气质。

这个issue可以关了吗？
